server:
  port: 8044
spring:
  cloud:
    schemaRegistryClient:
      endpoint: http://localhost:8081
    stream:
      default:
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
      bindings:
        alert-input:
          destination: alert10
          content-type: application/*+avro
          group: group-2
          concurrency: 3
          binder: kafka
        asset-input:
          destination: asset003
          content-type: application/*+avro
          group: group-1
          concurrency: 3
          binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            value:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
              serializer: org.apache.kafka.common.serialization.StringSerializer
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.LongSerializer
            value.serializer: org.apache.kafka.common.serialization.StringSerializer
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
